server:
  port: 8080
spring:
  application:
    name: gate-way-service
  cloud:
    gateway:
      routes:
        - id: store_meets_service
          uri: http://localhost:8081
          predicates:
            - Path=/store_meet
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka