server:
  address: localhost
  port : 8083
spring:
  application:
    name: Authorization_Authentication
  datasource:
    url: jdbc:postgresql://localhost:5432/cmeet
    username: frank
    password: frank2a4s56
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka